In [1]:
import numpy as np
def print_val(x):
    print "Type: ", type(x)
    print "Shape:" , x.shape
    print "값: \n", x
    print " "

In [4]:
#rank 1 np array
#x=np.array([1,2,3])
x=np.array([1,2,3,4])
print_val(x)

x[0]=5
print_val(x)

Type:  <type 'numpy.ndarray'>
Shape: (4,)
값: 
[1 2 3 4]
 
Type:  <type 'numpy.ndarray'>
Shape: (4,)
값: 
[5 2 3 4]
 


In [10]:
#rank2 np array
y=np.array([[1,2,3],[4,5,6]]) #행 2 열 3
print_val(y)

#0으로 초기화해야하는 경우
a=np.zeros((2,2)) #전달 인자로 shape를 넣어준다.
print_val(a)

#1로 초기화해야하는 경우
a=np.ones((3,2)) #전달 인자로 shape를 넣어준다. 3x2 tensor에다가
print_val(a)

#단위행렬
a=np.eye(4,5) #다른것과 쓰는법이 다르다
print_val(a)

Type:  <type 'numpy.ndarray'>
Shape: (2, 3)
값: 
[[1 2 3]
 [4 5 6]]
 
Type:  <type 'numpy.ndarray'>
Shape: (2, 2)
값: 
[[0. 0.]
 [0. 0.]]
 
Type:  <type 'numpy.ndarray'>
Shape: (3, 2)
값: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]
 
Type:  <type 'numpy.ndarray'>
Shape: (4, 5)
값: 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]
 


In [14]:
#랜덤행렬 만들기
a=np.random.random((4,4)) #0~1까지의 값이 선택될 확률이 모두 같다. shape만 지정해주면됨.
print_val(a)

a=np.random.randn(4,4) #0~1까지 값 나올 확률이 가우시안 분포를 따름
print_val(a)

Type:  <type 'numpy.ndarray'>
Shape: (4, 4)
값: 
[[0.91041979 0.46826893 0.26332804 0.72349431]
 [0.31235395 0.54511623 0.1948002  0.60010513]
 [0.993385   0.20672167 0.81576146 0.12269176]
 [0.20325834 0.78950743 0.24844178 0.28926426]]
 
Type:  <type 'numpy.ndarray'>
Shape: (4, 4)
값: 
[[ 0.63688701 -0.4982021  -0.72781565  2.34360945]
 [ 0.82298034 -2.50402068 -0.70569868 -0.87733803]
 [-0.5177229   0.3627289   1.78058063  1.02864351]
 [ 1.53481563  0.27891673 -0.86002203 -1.07516024]]
 


In [17]:
#인덱스를 통해 원소에 접근하기
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print_val(a)

b=a[:2,1:3] #,기준으로 앞에가 행, 뒤에는 열//행 0~1, 열 1~2//:2는 2직전까지 보겠다.
print_val(b)

row1=a[1,:]# : -> 모든 값 // 1행 전부를 원한다는 의미
print_val(row1)

Type:  <type 'numpy.ndarray'>
Shape: (3, 4)
값: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 
Type:  <type 'numpy.ndarray'>
Shape: (2, 2)
값: 
[[2 3]
 [6 7]]
 
Type:  <type 'numpy.ndarray'>
Shape: (4,)
값: 
[5 6 7 8]
 


In [22]:
#행렬 연산
m1=np.array([[1,2],[3,4]],dtype=np.float64)
m2=np.array([[5,6],[7,8]], dtype=np.float64)

#elementwise sum, 더하기//elementwise: 같은 위치의 원소끼리 더하겠다는 의미
print_val(m1+m2)
print_val(np.add(m1,m2)) #둘이 같은말..

#elementwise difference, 빼기
print_val(m1-m2)
print_val(np.subtract(m1,m2))

#elementwise product, 곱하기
print_val(m1*m2)
print_val(np.multiply(m1,m2))

#elementwise division, 나누기
print_val(m1/m2)
print_val(np.divide(m1,m2))

#elementwise square root, 루트 씌우기
print_val(np.sqrt(m1))
print_val(np.sqrt(m2))

Type:  <type 'numpy.ndarray'>
Shape: (2, 2)
값: 
[[ 6.  8.]
 [10. 12.]]
 
Type:  <type 'numpy.ndarray'>
Shape: (2, 2)
값: 
[[ 6.  8.]
 [10. 12.]]
 
Type:  <type 'numpy.ndarray'>
Shape: (2, 2)
값: 
[[-4. -4.]
 [-4. -4.]]
 
Type:  <type 'numpy.ndarray'>
Shape: (2, 2)
값: 
[[-4. -4.]
 [-4. -4.]]
 
Type:  <type 'numpy.ndarray'>
Shape: (2, 2)
값: 
[[ 5. 12.]
 [21. 32.]]
 
Type:  <type 'numpy.ndarray'>
Shape: (2, 2)
값: 
[[ 5. 12.]
 [21. 32.]]
 
Type:  <type 'numpy.ndarray'>
Shape: (2, 2)
값: 
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
 
Type:  <type 'numpy.ndarray'>
Shape: (2, 2)
값: 
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
 
Type:  <type 'numpy.ndarray'>
Shape: (2, 2)
값: 
[[1.         1.41421356]
 [1.73205081 2.        ]]
 
Type:  <type 'numpy.ndarray'>
Shape: (2, 2)
값: 
[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]
 
